#########################################################################################
# INVENTORY
#########################################################################################
FROZEN_INVENTORY:
  TITLE: "&4&lYou're frozen!"
  SEPARATORS:
    SIZE: 15
    COLOR: "&7&m"
  LORE:
    - "%separators%"
    - "&dYou are frozen!"
    - "&dJoin &e%ts_ip%"
    - "&dor else it will"
    - "&dresult in a &cban&d."
    - "%separators%"
#########################################################################################