name: DarkFreeze
version: ${project.version}
main: net.oculate.darkfreeze.DarkFreeze
authors: [Rhian]
description: Freeze plugin for the Oculate Network
website: www.oculate.net
commands:
  freeze:
    usage: "/freeze <Player>"
    aliases: [ss]
permissions:
  oculate.staff.freeze:
    description: Give staff permission to this command